KS-6-1 решение для 1 задачи, в которой проверяется логин и пароль пользователя при авторизации
mondayseptember/KotlinSprint pull request #22
Opened 2023-12-17 15:15 UTC by mondayseptember

2023-12-17 17:38 UTC, ievetrovdev requested changes

2023-12-17 17:38 UTC, ievetrovdev commented on src/main/kotlin/lesson_6/lesson6_task1.kt
> +    while ((userLogin != login && userPassword != password) ||
Давай оптимизируем. Если использовать do while, то сначала в цикле будет производиться запрос логина и пароля, а в условии цикла проверка "пока логин и пароль не равны введенным значениям".
Таким образом сообщение об успешной авторизации можно выводить после цикла, тк если он остановится и программа продолжит работу - значит пользователь ввел верные данные.
Так же попробуй упростить if

2023-12-18 05:54 UTC, mondayseptember commented on src/main/kotlin/lesson_6/lesson6_task1.kt
> +    while ((userLogin != login && userPassword != password) ||
исправила на do while, а вот как упростить условие, не совсем поняла(

2023-12-18 07:15 UTC, ievetrovdev requested changes

2023-12-18 07:15 UTC, ievetrovdev commented on src/main/kotlin/lesson_6/lesson6_task1.kt
> +    } while (((userLogin != login) && (userPassword != password)) ||
Смотри для продолжения цикла нужно чтобы хотя бы одно из полей было false, следовательно хватит 
`(userLogin != login || userPassword != password)`

2023-12-18 07:54 UTC, mondayseptember commented on src/main/kotlin/lesson_6/lesson6_task1.kt
> +    } while (((userLogin != login) && (userPassword != password)) ||
исправила, спасибо!

2023-12-18 16:37 UTC, ievetrovdev commented on src/main/kotlin/lesson_6/lesson6_task1.kt
> +    } while (((userLogin != login) && (userPassword != password)) ||
Отлично
, молодец

2023-12-18 16:37 UTC, ievetrovdev approved these changes

2023-12-19 04:54 UTC, merged