KS-6-2 решение для 2 задачи, в которой cоздан простой таймер
mondayseptember/KotlinSprint pull request #23
Opened 2023-12-17 15:20 UTC by mondayseptember

2023-12-17 17:39 UTC, ievetrovdev requested changes

2023-12-17 17:39 UTC, ievetrovdev commented on src/main/kotlin/lesson_6/lesson6_task2.kt
> +    while (countOfSec > 0) {
По условию вроде не нужно делать цикл. Может можно обойтись одним вызовом sleep?)

2023-12-18 05:58 UTC, mondayseptember commented on src/main/kotlin/lesson_6/lesson6_task2.kt
> +    while (countOfSec > 0) {
как в sleep можно присвоить значение, которое ввел пользователь?

2023-12-18 07:18 UTC, ievetrovdev requested changes

2023-12-18 07:18 UTC, ievetrovdev commented on src/main/kotlin/lesson_6/lesson6_task2.kt
> +    Thread.sleep(1000)
У тебя есть количество секунд, следовательно в sleep надо передать произведение countOfSec и 1000, получим секунды в миллисекундах.

2023-12-18 07:54 UTC, mondayseptember commented on src/main/kotlin/lesson_6/lesson6_task2.kt
> +    Thread.sleep(1000)
спасибо!

2023-12-18 16:38 UTC, ievetrovdev commented on src/main/kotlin/lesson_6/lesson6_task2.kt
> +    Thread.sleep(1000)
Так держать!

2023-12-18 16:38 UTC, ievetrovdev approved these changes

2023-12-19 04:55 UTC, merged