KS-9-4 решение для 4 задачи, в которой запрашивается пять названий ингредиентов в одной строке
mondayseptember/KotlinSprint pull request #37
Opened 2023-12-21 19:53 UTC by mondayseptember

2023-12-21 19:56 UTC, mondayseptember commented
Не получилось разобраться как запрашивать "пять названий ингредиентов блюда в одной строке, разделяя их запятыми". Сейчас все элементы запрашиваются с новой строки

2023-12-22 17:52 UTC, ievetrovdev requested changes

2023-12-22 17:52 UTC, ievetrovdev commented on src/main/kotlin/lesson_9/lesson9_task4.kt
> +    val listOfIngredients = listOf("", "", "", "", "")
Попробуй посмотреть в сторону функции split(", "), помнишь было в 3 уроке)

2023-12-23 10:39 UTC, ievetrovdev approved these changes

2023-12-24 16:27 UTC, merged