KS-21-1 решение 1 задачи, в которой создана extension функция для класса String
mondayseptember/KotlinSprint pull request #82
Opened 2024-01-28 10:08 UTC by mondayseptember

2024-01-31 02:49 UTC, ievetrovdev requested changes

2024-01-31 02:49 UTC, ievetrovdev commented on src/main/kotlin/lesson_21/lesson21_task1.kt
> +    for (i in word.lowercase()) {
можно сильно сократить функцию, сделав таким образом:
```
fun String.vowelCount(): Int {
    return count { it in "aeiou" }
}
```

2024-02-01 19:19 UTC, mondayseptember commented on src/main/kotlin/lesson_21/lesson21_task1.kt
> +    for (i in word.lowercase()) {
круто, спасибо!)

2024-02-02 00:08 UTC, ievetrovdev approved these changes

2024-02-06 19:50 UTC, merged