KS-21-4 решение 4 задачи, в которой создана extension функцию для класса File
mondayseptember/KotlinSprint pull request #85
Opened 2024-01-29 17:25 UTC by mondayseptember

2024-01-29 17:26 UTC, mondayseptember commented
Не получилось разобраться как записывать текст в начало файла

2024-01-31 02:56 UTC, ievetrovdev requested changes

2024-01-31 02:56 UTC, ievetrovdev commented on src/main/kotlin/lesson_21/lesson21_task4.kt
> +    appendText(word.lowercase())
попробуй использовать функцию `writeText`
таким образом:
`this.writeText(word.lowercase() + this.readText())`

2024-02-01 19:21 UTC, mondayseptember commented on src/main/kotlin/lesson_21/lesson21_task4.kt
> +    appendText(word.lowercase())
спасибо!

2024-02-02 00:08 UTC, ievetrovdev approved these changes

2024-02-06 19:51 UTC, merged